# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 632c7df58651eaff1d307056ff3eb0a1ac6f763788bdede104cb678bfcca50075ac4bbdb682c04f87651b9401ef99a21d0a225139d4148899def3c5f78f4f9d7

test:
  secret_key_base: 2f17cb0085c430d909f1e2fc543b5d8645338d5083c2095860a23bddaf19cea31755458f19c3613b9a7c4b8f31a97b872186cdde55836d6b3136b172304bf189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
